### ISSUE TITLE
`NO_LEGEND` should imply `show stereotype`

### ISSUE THREAD

**Issue by cprn** [skleanthous/C4-PlantumlSkin#10]
Hi there! First of all, outstanding job. I have only one minor issue that'll spawn 2 tickets. This is the first one.

```puml
!define NO_LEGEND
```
While it indeed hides the legend, without it it's hard to see what's what. It would be clearer if stereotype was displayed in that case. Obviously I can achieve that by calling `show stereotype` at the beginning of the diagram but it quickly become obvious I need it on every diagram that lacks legend. I can make a PR if you agree it should be visible when there's no legend.

**Comment by skleanthous** [comment]
Hello @cprn, 

First of all thank you!

As for showing the stereotype when `NO_LEGEND` is defined, it's a good point, and I agree. Feel free to make a PR about this.
