### ISSUE TITLE
skinparam defaultTextAlignment center

### ISSUE THREAD

**Issue by cprn** [skleanthous/C4-PlantumlSkin#11]
I quickly noticed I paste it on every diagram. Would be nice to have it in the skin by default.

```puml
skinparam defaultTextAlignment center
show stereotype
```

Current:
![image](https://user-images.githubusercontent.com/6132708/66921999-7ee6f700-f026-11e9-819a-6f3757bc247c.png)

Target:
![image](https://user-images.githubusercontent.com/6132708/66921910-59f28400-f026-11e9-97f0-2ba408464301.png)

**Comment by skleanthous** [comment]
The stereotype part I believe is covered by the issue #10 you raised.

As for text alignment, also sounds good. Feel free to create a PR for this too. Also, not problem if these are combined.

**Comment by skleanthous** [comment]
The only comment I'd add is that I believe that the stereotype should adhere to the font colouring of the item it's in already.
