### ISSUE TITLE
enable legend deactivation

### ISSUE THREAD

**Issue by mick352** [skleanthous/C4-PlantumlSkin#15]
Hi, thanks for the nice tool. It would be nice if the legend could be disabled. 

Just FYI: this kept me from using it.

**Comment by skleanthous** [comment]
Hello Mick,

Just define `!define NO_LEGEND` immediately _before_ the include statement. [See this in planttext diagram for an example](https://www.planttext.com/?text=TP91JyCm38Nl-HNU2JXqkUo4gWc93JG9ZOaT4K9fuhNHKcTA70R_dcwexQQMtEBt_DbFoKDa5JZLJamCxYmXh5y_NvRFo_L2Y8abxPB151nKp8TuBsLGnsbfkKf5YXYq9qRYgVQrZ7k7YhZoASh7MRPnpQK1R_UMPAqYOv15iiv8d_YGMEhPz70QB09gLbGwX5L32wJSMrV9yxO6sv-6KS_d5_xbzz3Vrdg_s0LLz_2dyotFE_rFRljQUOHZJuITqZrhrLKkUBsjPLpQHhZ3s905MrQSpM6OKLm7EP-X_IoAuPuZrauKuWOsFbgsdYoLK3L98jmQVoJGYg10K4KHyCigHWFiOG78-cuaGFPUMMEGFaxDpR2hdKSI_EVlTxj-dx6UOPu79DDyiLy0)

**Comment by skleanthous** [comment]
If that's OK with you let me know so that I can close the issue.

**Comment by mick352** [comment]
Awesome, thanks! https://github.com/skleanthous/C4-PlantumlSkin/pull/16 should adjust the README. Feel free to do as you see fit with it.
